_wandb:
    value:
        cli_version: 0.21.0
        e:
            ab7t7sko5113psbr64svvjsus1obkx2w:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "6442450944"
                codePath: scripts/train.py
                codePathLocal: scripts/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "238694543360"
                email: 232104@iiitt.ac.in
                executable: /Users/vighneshms/Downloads/Virtual Environments/ar/bin/python3
                git:
                    commit: eb8abcd2e329d501486d7dcf9b6d28518d2d3979
                    remote: https://github.com/Vighnesh-M-S/UNet_Model.git
                host: VIGHNESHsLaptop.lan
                memory:
                    total: "8589934592"
                os: macOS-14.2-arm64-arm-64bit-Mach-O
                program: /Users/vighneshms/Downloads/UNet_Model/scripts/train.py
                python: CPython 3.13.4
                root: /Users/vighneshms/Downloads/UNet_Model
                startedAt: "2025-08-06T16:18:51.894757Z"
                writerId: ab7t7sko5113psbr64svvjsus1obkx2w
        m: []
        python_version: 3.13.4
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 13
                - 16
            "4": 3.13.4
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
batch_size:
    value: 16
epochs:
    value: 50
image_size:
    value: 128
lr:
    value: 0.001
model:
    value: UNet
